symspec = struct(                              ...
    'border', makesymbolspec(                  ...
        'Line',                                ...
            { 'Default',                       ...
                'Color', [.9 .7 .7],           ...
                'LineWidth', 2,                ...
            }                                  ...
    ),                                         ...
    'roads', makesymbolspec(                   ...
        'Line',                                ...
            { 'Default',                       ...
                'Color', [.4 .4 .4]            ...
            }                                  ...
    ),                                         ...
    'cities', makesymbolspec(                  ...
        'Point',                               ...
            { 'Default',                       ...
                'Marker', 'o'                  ...
                'MarkerEdgeColor', white(1),   ...
                'MarkerFaceColor', [1 0 0],    ...
                'MarkerSize', 8,               ...
            }                                  ...
    ),                                         ...
    'towns', makesymbolspec(                   ...
        'Point',                               ...
            { 'Default',                       ...
                'Marker', 'o'                  ...
                'MarkerEdgeColor', white(1),   ...
                'MarkerFaceColor', [0 0 1],    ...
                'MarkerSize', 4,               ...
            }                                  ...
    )                                          ...
);