%SYMBOLSPEC.M A térképi megjelenítéshez szükséges jelkulcsi adatok.
%
% (C) GPLv2 Barancsuk Ádám, 2013

symspec = struct(                              ...
    'border', makesymbolspec(                  ...  % Határok
        'Line',                                ...
            { 'Default',                       ...
                'Color', [.9 .7 .7],           ...
                'LineWidth', 2,                ...
            }                                  ...
    ),                                         ...
    'border2', makesymbolspec(                 ...  % Torzított határok
        'Line',                                ...
            { 'Default',                       ...
                'Color', [1 .5 .5],            ...
                'LineWidth', 2,                ...
            }                                  ...
    ),                                         ...
    'roads', makesymbolspec(                   ...  % Utak
        'Line',                                ...
            { 'Default',                       ...
                'Color', [.4 .4 .4]            ...
            }                                  ...
    ),                                         ...
    'cities', makesymbolspec(                  ...  % Városok
        'Point',                               ...
            { 'Default',                       ...
                'Marker', 'o'                  ...
                'MarkerEdgeColor', white(1),   ...
                'MarkerFaceColor', [1 0 0],    ...
                'MarkerSize', 8,               ...
            }                                  ...
    ),                                         ...
    'towns', makesymbolspec(                   ...  % Kisvárosok
        'Point',                               ...
            { 'Default',                       ...
                'Marker', 'o'                  ...
                'MarkerEdgeColor', white(1),   ...
                'MarkerFaceColor', [0 0 1],    ...
                'MarkerSize', 4,               ...
            }                                  ...
    ),                                         ...
    'cities_original', makesymbolspec(         ...  % Kontrollpontok (eredeti)
        'Point',                               ...
            { 'Default',                       ...
                'Marker', 'o'                  ...
                'MarkerEdgeColor', white(1),   ...
                'MarkerFaceColor', [0 0 1],    ...
                'MarkerSize', 6,               ...
            }                                  ...
    ),                                         ...
    'cities_transformed', makesymbolspec(      ...  % Kontrollpontok (torzított)
        'Point',                               ...
            { 'Default',                       ...
                'Marker', 'o'                  ...
                'MarkerEdgeColor', white(1),   ...
                'MarkerFaceColor', [1 0 0],    ...
                'MarkerSize', 6,               ...
            }                                  ...
    ),                                         ...
    'traces', makesymbolspec(                  ...  % Kontrollpontok "nyoma" a torzítás folyamán
        'Point',                               ...
            { 'Default',                       ...
                'Marker', 'o'                  ...
                'MarkerEdgeColor', white(1),   ...
                'MarkerFaceColor', [.5 .5 .5], ...
                'MarkerSize', 4,               ...
            }                                  ...
    )                                          ...
);