#!/usr/bin/env bash

RETVAL_EX_USAGE=64
RETVAL_EX_NOINPUT=66
RETVAL_ERROR=1

GETOPT_SHORT="sv"
GETOPT_LONG="write-file:,wf:,write-psql:,wp:,psql-schema:,ps:,truncate-psql,tp,sanitize,s,verbose,v"

SANITIZE_XSL='./sanitize-osm.xsl'

FILTERED_SUFFIX='filtered'
SANITIZED_SUFFIX='sanitized'

POSTGRES_DEFAULT_SCHEMA='pgsql'


[ $# -gt 0 ] || {
	echo "Preprocess OSM data for the time-distance mapping algorithm."
	echo ""
	echo "Usage: $(basename $0) "
	echo "	[--write-file | --wf] file               -- Specify output file name"
	echo "	[--write-psql | --wp] database           -- Specify output PostgreSQL database"
	echo "	[--psql-schema | --ps] {pgsql,pgsimp}    -- Specify PostgreSQL schema"
	echo "	[--truncate-psql | --tp]                 -- Truncate PostgresSQL database before importing"
	echo "	[--sanitize | -s]                        -- Sanitize output XML minimizing file size"
	echo "	[--verbose | -v]                         -- Output debug information"
	echo "	file.osm                                 -- Input file name"
	exit $RETVAL_EX_USAGE
}


OPTS=$(getopt -u -o "$GETOPT_SHORT" -l "$GETOPT_LONG" -n "`basename $0`" -- "$@")

[ $? = 0 ] || {
	echo >&2 "Error parsing arguments."
	exit $RETVAL_ERROR
}

set -- $OPTS

while [ $# -gt 0 ]; do
    case $1 in
		--wf | --write-file)          outfile=$2;      shift;;
		--wp | --write-psql)          psql_db=$2;      shift;;
		--ps | --psql-schema)
			[ "$psql_schema" = 'pgsimp' -o "$psql_schema" = 'pgsql' ] && psql_schema=$2 || {
				echo "Invalid PostgreSQL schema."
				exit $RETVAL_ERROR
			}
			shift;;
		--tp | --truncate-psql)       truncate=1;;
		-s   | --sanitize)            sanitize=1;;
		-v	 | --verbose)             verbose=1;;

		(--) shift; break;;
		(*) break;;
    esac
    shift
done

infile=$1

[ "$infile" != '' -a -f "$infile" ] || {
	echo >&2 "File '$infile' does not exist."
	exit $RETVAL_EX_NOINPUT
}

command -v osmosis > /dev/null 2>&1 || {
	echo >&2 "Cannot find osmosis. Aborting."
	exit $RETVAL_EX_ERROR
}

command -v xsltproc >/dev/null 2>&1 
[ "$sanitize" = '1' -a $? -ne '0' ] && {
	echo >&2 "Sanitization is enabled but xsltproc cannot be found. Aborting."
	exit $RETVAL_EX_ERROR
}

[ $verbose ] && osmosis_verbose='-verbose 100' || osmosis_verbose='-verbose 0'
osmosis_cmd="osmosis $osmosis_verbose --read-xml $infile "

if [ $psql_db ]; then

	source ../psql.conf

	psql_schema=${psql_schema:-$POSTGRES_DEFAULT_SCHEMA}
	psql_authinfo="
		host=$PG_HOST \
		user=$PG_USER \
		password=$PG_PASSWORD \
		database=$psql_db \
		validateSchemaVersion=no"

	[ $truncate ] && {
		osmosis_truncate_cmd="osmosis --truncate-$psql_schema $psql_authinfo"
		[ $verbose ] && { echo; echo *****; echo $osmosis_truncate_cmd; echo *****; echo; }
		$osmosis_truncate_cmd
	}

	osmosis_cmd="$osmosis_cmd --write-$psql_schema $psql_authinfo"

else

	outfile=${outfile:-${infile%.bz2}}
	outfile=${outfile%.osm}-$FILTERED_SUFFIX.osm

	osmosis_cmd="$osmosis_cmd \
		--compute-bounding-box \
		--write-xml $outfile"

fi

[ $verbose ] && { echo; echo *****; echo $osmosis_cmd; echo *****; echo; }
$osmosis_cmd

if [ "$sanitize" != '' -a "$psql_db" = '' ]; then
	sanitize_outfile=${outfile%.osm}-$SANITIZED_SUFFIX.osm
	xsltproc $SANITIZE_XSL $outfile > $sanitize_outfile
	rm $outfile
fi
